In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from IPython.display import Image
from IPython.core.display import HTML

In [3]:
%%bash

rm -r ./__collection__/* || true

In [13]:
! python main/data/generator/Executor.py -i . -o ./__collection__

1 POLYGON ((1397.880004882812 508.7200012207031, 1397.880004882812 386.6300048828125, 1336.93994140625 386.6300048828125, 1336.93994140625 508.7200012207031, 1397.880004882812 508.7200012207031))
11 POLYGON ((1300.77001953125 1287.5400390625, 1300.77001953125 930.0800170898438, 937.5900268554688 930.0800170898438, 937.5900268554688 1287.5400390625, 1300.77001953125 1287.5400390625))
11 POLYGON ((1294.81005859375 1470.630004882812, 1294.81005859375 1298.5400390625, 1158.349975585938 1298.5400390625, 1158.349975585938 1470.630004882812, 1294.81005859375 1470.630004882812))
11 POLYGON ((1300.77001953125 1287.5400390625, 1300.77001953125 930.0800170898438, 937.5900268554688 930.0800170898438, 937.5900268554688 1287.5400390625, 1300.77001953125 1287.5400390625))
x
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0.,

e:\DATA\CHRISTIAN\KULIAH\TA\code\dataset\main\data\generator\FloorPlanSVG.py:184: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  center = ShapeCentroid(furniture['bound'])


In [61]:
import numpy as np

x = np.arange(9)
x2 = np.reshape(x, (3, 3))
display(x2, np.roll(x2, (1,1), axis=(1,0)))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[8, 6, 7],
       [2, 0, 1],
       [5, 3, 4]])

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
import os, cv2
import matplotlib.pyplot as plt
import numpy as np
import src.HouseConfig as Mapper

def viewPoly(task, mapper, pick=3):
    for filename in os.scandir(f'./__collection__/{task}/image'):
        if filename.is_file():
            [ID, folder, type, ext] = filename.name.split('.')

            with open(f'./__collection__/{task}/label/{ID}.label.{type}.txt') as f:
                lines = f.read().split('\n')
            
            img = cv2.imread(f'./__collection__/{task}/image/{filename.name}')
            shape = 416
            
            pts = []
            for line in lines:
                poly = np.round(np.array(list(map(float, line.split(' ')))) * 416).astype(int)
                pts.append(np.array([np.clip(poly[2::2], 0,415), np.clip(poly[1::2], 0,415)]).T.reshape((-1, 1, 2)))
                if mapper is not None:
                    cv2.putText(img, mapper(int(poly[0] // 416)), (poly[4], poly[3]), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)

            img = cv2.polylines(img, pts, True, (255, 0, 0), 2)

            plt.figure(figsize=(12,12))
            plt.imshow(img[:,:,::-1])

options = [
    ('boundary-segmentation', Mapper.getBoundaryName),
    ('symbol-detection', Mapper.getRoomName),
    ('roi-detection', None)
]

it = int(input())
viewPoly(options[it][0], options[it][1])

ValueError: invalid literal for int() with base 10: ''