In [4]:
import os
import numpy as np
from sklearn.model_selection import train_test_split


files = []
for file in os.scandir('./__collection__/room-classification/graph'):
    if file.is_file():
        files.append(file.name.split('.')[0])
files = np.array(files)

N = files.shape[0]
test_ratio, validation_ratio = 0.15, 0.15


np.random.shuffle(files)

data = {}
split_1 = int(N * test_ratio)
split_2 = split_1 + int(N * validation_ratio)
data['test'] = files[0: split_1]
data['validation'] = files[split_1: split_2]
data['train'] = files[split_2:]


for task in ['test', 'validation', 'train']:
    with open(f'./__collection__/room-classification/{task}.txt', 'w') as f:
        for idx,file in enumerate(data[task]):
            if idx > 0:
                f.write('\n')
            f.write(file)

In [67]:
from torch_geometric.data import data
import torch

root = '__collection__\\room-classification'

with open(f'{root}\\validation.txt') as f:
    files = f.read().split('\n')

filt_room = np.array([1,3,4,5,6,7,9,10,11,12])
hist = np.zeros(10, dtype=np.int32)
cnt = 0
for file in files:
    break
    path = f'{root}\\graph\\{file}.pt'
    graph = torch.load(path)
    graph.x = graph.x[:,[i for i in range(20) if i != 9]]

    torch.save(graph, path)

hist

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
from main.data.dataclass.RoomDataset import RoomDataset
import numpy as np

train_dataset = RoomDataset(root='__collection__\\room-classification', filenames='train.txt')
cnt = 0
for data in train_dataset:
    if data.y.size()[0] > 0:
        u, v = np.unique(data.y.argmax(-1).numpy(), return_counts=True)
        hist[u] += v

cnt,hist

(0,
 array([3987, 2485,  569, 4556, 3826, 3302, 2566,  356, 4627, 2303,    0,
           0,    0]))

In [6]:
from shapely.geometry.linestring import LineString
import numpy as np

np.array(LineString([(0, 0), (1, 1)]).xy).T

array([[0., 0.],
       [1., 1.]])

In [1]:
! conda list -e > requirements.txt

In [1]:
! pip install ultralytics

  Using cached ultralytics-8.0.61-py3-none-any.whl (490 kB)
  Using cached seaborn-0.12.2-py3-none-any.whl (293 kB)
  Using cached opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.5.5


ERROR: Cannot uninstall opencv-python 4.5.5, RECORD file not found. Hint: The package was installed by conda.


In [ ]:
! python main/trainer.py --epochs=10 --trials=1 --architecture=graph-sage

In [1]:
import torch
torch.__version__

'1.12.1'

In [9]:
import torch.nn.functional as F

input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=-1)
loss = F.cross_entropy(input, target)

display(input, target)

tensor([[ 0.3340, -0.0961, -1.3326,  0.1321, -0.4851],
        [ 0.0685,  0.4007, -0.1671, -1.2219, -0.8060],
        [ 0.8905,  0.1483,  1.0729, -0.1680, -0.9641]], requires_grad=True)

tensor([[0.0599, 0.3273, 0.2355, 0.2141, 0.1632],
        [0.0643, 0.1398, 0.1598, 0.5299, 0.1061],
        [0.2782, 0.2841, 0.0650, 0.1671, 0.2056]])

In [ ]:
import torch
torch.load